### ISSUE TITLE
Does not display data on streamlit-tabl-select-cell from your demo app in streamlit 1.37.0

### ISSUE THREAD

**Issue by hl5biw** [songjinghe/streamlit-table-select-cell#1]
Name: streamlit
Version: 1.37.0
![image](https://github.com/user-attachments/assets/66390f4d-d3c0-4bf4-891d-29b2ae775d85)

**Comment by dmcskim** [comment]
I second this issue. Component is not functional.

**Comment by IrinaFikh** [comment]
Not works

**Comment by songjinghe** [comment]
I develop this on streamlit 1.30.0. It works well on it. Let me have look at streamlit new version.
![plugin running on streamlit 1.30.0](https://github.com/user-attachments/assets/6254f01f-6039-4ea8-9891-42760779b926)

**Comment by IrinaFikh** [comment]
Thank you very much for your reaction.
I will connect you after few days (now off), have a nice day,
Irina

**Comment by songjinghe** [comment]
confirmed

**Comment by IrinaFikh** [comment]
Hi, I use streamlit 1.38.0 and your example.
See please 
![inspect](https://github.com/user-attachments/assets/80f95ca2-ec9c-4f14-bf05-ddb4983812f5)
![visualization](https://github.com/user-attachments/assets/dd8e9306-397c-4cba-b3d8-3fe21220eaca)

**Comment by IrinaFikh** [comment]
Any my actions with GUI cannot change this state.

Thanks!

**Comment by jamsnrihk** [comment]
why has "False" status?
![image](https://github.com/user-attachments/assets/da4df37b-0197-428d-87c4-5fa8ce8e2aa1)

**Comment by songjinghe** [comment]
> Hi, I use streamlit 1.38.0 and your example. See please 

Please upgrade this plugin to version 0.3.4 which fix this issue. @IrinaFikh

**Comment by songjinghe** [comment]
> why has "False" status? 
please provide your code to locate the problem @jamsnrihk

**Comment by IrinaFikh** [comment]
Hi, thank you again, after upgrade it's ok. There is your example code, not my :)
Closed
