### ISSUE TITLE
Does not display data on streamlit-tabl-select-cell from your demo app in streamlit 1.38.0

### ISSUE THREAD

**Issue by IrinaFikh** [songjinghe/streamlit-table-select-cell#2]
![inspect](https://github.com/user-attachments/assets/35275f29-8ee3-4010-bc8f-fbf4acd73cc9)
![visualization](https://github.com/user-attachments/assets/897a9107-e85f-4585-a9f4-03001c4ccb92)

**Comment by songjinghe** [comment]
please upgrade streamlit-tabl-select-cell to version 0.3.4, which fix this problem

**Comment by IrinaFikh** [comment]
Yes, thank you very much, close this issue
